
// Generate enum definitions from all data sheets.

public enum SheetName
{
     T_BattleEnemyData,
     T_BattleSceneData,
     T_BattleStageData,
     T_BossPhaseData,
     T_BuffData,
     T_CharacterData,
     T_CharacterStatData,
     T_DialogueSciprtTextData,
     T_DialogueScriptData,
     T_EffectData,
     T_FieldData,
     T_GlobalValueData,
     T_ItemData,
     T_LocalStringData,
     T_MonsterGimmickData,
     T_MonsterGrroupMemberData,
     T_MonsterPresetData,
     T_MonsterSpawnData,
     T_MonsterStatData,
     T_NpcData,
     T_ProjectileData,
     T_QuestActionData,
     T_QuestConditionData,
     T_QuestData,
     T_QuestStepData,
     T_RewardData,
     T_RewardGroupData,
     T_SkillData,
     T_SkillEffectData,
     T_SkillHitData,
     T_SkilTreeNodelData,
     T_SkilTreeUnlockData,
     T_StatData,
     T_StringData,
     T_UnitData,
}
